// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260721234721_AddUserPasswordHash")]
    partial class AddUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.BranchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId", "Name");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.InventoryItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ReorderPoint")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("reorder_point");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ticks");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BranchId", "ProductId")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.InventoryMovementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("inventory_item_id");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at_utc_ticks");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<decimal>("QuantityAfter")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_after");

                    b.Property<decimal>("QuantityBefore")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_before");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_id");

                    b.Property<Guid?>("SaleLineId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_line_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("movement_type");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleLineId");

                    b.HasIndex("BranchId", "ProductId");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.OrganizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<long>("PaidAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paid_at_utc_ticks");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_id");

                    b.HasKey("Id");

                    b.HasIndex("Method");

                    b.HasIndex("PaidAtUtc");

                    b.HasIndex("SaleId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_currency");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("SalePriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price_amount");

                    b.Property<string>("SalePriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price_currency");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<bool>("TracksInventory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tracks_inventory");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId", "Barcode");

                    b.HasIndex("OrganizationId", "Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RegisterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("BranchId", "Name");

                    b.ToTable("registers", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RegisterSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal?>("CashDifferenceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_difference_amount");

                    b.Property<string>("CashDifferenceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_difference_currency");

                    b.Property<long?>("ClosedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("closed_at_utc_ticks");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_by_user_id");

                    b.Property<decimal?>("CountedCashAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("counted_cash_amount");

                    b.Property<string>("CountedCashCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("counted_cash_currency");

                    b.Property<decimal?>("ExpectedCashAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_cash_amount");

                    b.Property<string>("ExpectedCashCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_cash_currency");

                    b.Property<long>("OpenedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opened_at_utc_ticks");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_by_user_id");

                    b.Property<decimal>("OpeningFloatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_float_amount");

                    b.Property<string>("OpeningFloatCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_float_currency");

                    b.Property<Guid>("RegisterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("register_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAtUtc");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("OpenedAtUtc");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("RegisterId");

                    b.HasIndex("Status");

                    b.ToTable("register_sessions", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RolePermissionRecord", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RoleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.SaleLineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_sku");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price_amount");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleId", "ProductId")
                        .IsUnique();

                    b.ToTable("sale_lines", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.SaleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_id");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc_ticks");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RegisterSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("register_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_status");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RegisterSessionId");

                    b.HasIndex("Status");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("RoleId");

                    b.HasIndex("OrganizationId", "Username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.BranchRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.InventoryItemRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.BranchRecord", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.InventoryMovementRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.InventoryItemRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.SaleRecord", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Infrastructure.Persistence.Records.SaleLineRecord", null)
                        .WithMany()
                        .HasForeignKey("SaleLineId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.PaymentRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.SaleRecord", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RegisterRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.BranchRecord", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RegisterSessionRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Infrastructure.Persistence.Records.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.RegisterRecord", null)
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RolePermissionRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.RoleRecord", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RoleRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.SaleLineRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.SaleRecord", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.SaleRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.BranchRecord", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.RegisterSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("RegisterSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.UserRecord", b =>
                {
                    b.HasOne("Pos.Infrastructure.Persistence.Records.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Infrastructure.Persistence.Records.RoleRecord", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.RoleRecord", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.Records.SaleRecord", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
